import assert from 'node:assert/strict';
import {chooseActiveFreezer,effectiveTheme,filterItems,formatQuantity,nextTheme,updateThemeButton} from '../../src/tiefkuehlliste/static/modules.js';
const parts=[{kind:'package',amount:1,package_size:1000,unit:'g'},{kind:'loose',amount:800,unit:'g'}];
assert.equal(formatQuantity(parts),'1 × 1000 g + 800 g');
assert.equal(formatQuantity([{kind:'loose',amount:2,unit:'piece'}]),'2 Stück');
assert.equal(filterItems([{product:'Brokkoli',parts,note:'offen'}],'800').length,1);
assert.equal(filterItems([{product:'Brokkoli',parts,note:'offen'}],'möhre').length,0);
assert.equal(effectiveTheme('system',true),'dark');assert.equal(effectiveTheme('system',false),'light');assert.equal(effectiveTheme('light',true),'light');
assert.equal(nextTheme('light'),'dark');assert.equal(nextTheme('dark'),'light');
const button={setAttribute(name,value){this[name]=value}};updateThemeButton(button,'dark');assert.equal(button.textContent,'☀');assert.match(button['aria-label'],/aktuell dunkel/);
assert.equal(chooseActiveFreezer([{id:1,is_default:1},{id:2,is_default:0}],null),1);
assert.equal(chooseActiveFreezer([{id:1,is_default:1},{id:2,is_default:0}],2),2);
console.log('JavaScript-Modultests erfolgreich');
